# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relation.proto',
  package='query_performance_estimator.qpe_proto',
  serialized_pb='\n\x0erelation.proto\x12%query_performance_estimator.qpe_proto\"\xc7\x04\n\x08Relation\x12\x42\n\x02op\x18\x01 \x01(\x0e\x32\x36.query_performance_estimator.qpe_proto.Relation.OpCode\x12\x42\n\trelations\x18\x02 \x03(\x0b\x32/.query_performance_estimator.qpe_proto.Relation\x12\x0c\n\x04rows\x18\x03 \x01(\x03\x12\r\n\x05width\x18\x04 \x01(\x03\x12\x0e\n\x06result\x18\x05 \x01(\x03\"\x85\x03\n\x06OpCode\x12\x08\n\x04JOIN\x10\x00\x12\x0b\n\x07MAPJOIN\x10\x01\x12\x0b\n\x07\x45XTRACT\x10\x02\x12\n\n\x06\x46ILTER\x10\x03\x12\x0b\n\x07\x46ORWARD\x10\x04\x12\x0b\n\x07GROUPBY\x10\x05\x12\t\n\x05LIMIT\x10\x06\x12\n\n\x06SCRIPT\x10\x07\x12\n\n\x06SELECT\x10\x08\x12\r\n\tTABLESCAN\x10\t\x12\x0c\n\x08\x46ILESINK\x10\n\x12\x0e\n\nREDUCESINK\x10\x0b\x12\t\n\x05UNION\x10\x0c\x12\x08\n\x04UDTF\x10\r\x12\x13\n\x0fLATERALVIEWJOIN\x10\x0e\x12\x16\n\x12LATERALVIEWFORWARD\x10\x0f\x12\x11\n\rHASHTABLESINK\x10\x10\x12\x12\n\x0eHASHTABLEDUMMY\x10\x11\x12\x07\n\x03PTF\x10\x12\x12\x07\n\x03MUX\x10\x13\x12\t\n\x05\x44\x45MUX\x10\x14\x12\t\n\x05\x45VENT\x10\x15\x12\x10\n\x0cORCFILEMERGE\x10\x16\x12\x0f\n\x0bRCFILEMERGE\x10\x17\x12\r\n\tMERGEJOIN\x10\x18\x12\x14\n\x10SPARKPRUNINGSINK\x10\x19\x12\x08\n\x04NONE\x10\x1a')



_RELATION_OPCODE = _descriptor.EnumDescriptor(
  name='OpCode',
  full_name='query_performance_estimator.qpe_proto.Relation.OpCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAPJOIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTRACT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILTER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUPBY', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIMIT', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCRIPT', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELECT', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TABLESCAN', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILESINK', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REDUCESINK', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNION', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UDTF', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LATERALVIEWJOIN', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LATERALVIEWFORWARD', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASHTABLESINK', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASHTABLEDUMMY', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PTF', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUX', index=19, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEMUX', index=20, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT', index=21, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORCFILEMERGE', index=22, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCFILEMERGE', index=23, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MERGEJOIN', index=24, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPARKPRUNINGSINK', index=25, number=25,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=26, number=26,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=252,
  serialized_end=641,
)


_RELATION = _descriptor.Descriptor(
  name='Relation',
  full_name='query_performance_estimator.qpe_proto.Relation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='query_performance_estimator.qpe_proto.Relation.op', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relations', full_name='query_performance_estimator.qpe_proto.Relation.relations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='query_performance_estimator.qpe_proto.Relation.rows', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='query_performance_estimator.qpe_proto.Relation.width', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='query_performance_estimator.qpe_proto.Relation.result', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RELATION_OPCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=641,
)

_RELATION.fields_by_name['op'].enum_type = _RELATION_OPCODE
_RELATION.fields_by_name['relations'].message_type = _RELATION
_RELATION_OPCODE.containing_type = _RELATION;
DESCRIPTOR.message_types_by_name['Relation'] = _RELATION

class Relation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RELATION

  # @@protoc_insertion_point(class_scope:query_performance_estimator.qpe_proto.Relation)


# @@protoc_insertion_point(module_scope)
