# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relation.proto',
  package='qpe.proto',
  serialized_pb='\n\x0erelation.proto\x12\tqpe.proto\"\xcb\x01\n\x08Relation\x12&\n\x02op\x18\x01 \x01(\x0e\x32\x1a.qpe.proto.Relation.OpCode\x12&\n\trelations\x18\x02 \x03(\x0b\x32\x13.qpe.proto.Relation\x12\x0c\n\x04rows\x18\x03 \x01(\x03\x12\r\n\x05width\x18\x04 \x01(\x03\x12\x0e\n\x06result\x18\x05 \x01(\x03\"B\n\x06OpCode\x12\x08\n\x04JOIN\x10\x00\x12\x0b\n\x07MAPJOIN\x10\x01\x12\x0b\n\x07\x45XTRACT\x10\x02\x12\n\n\x06\x46ILTER\x10\x03\x12\x08\n\x04NONE\x10\x1a')



_RELATION_OPCODE = _descriptor.EnumDescriptor(
  name='OpCode',
  full_name='qpe.proto.Relation.OpCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAPJOIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTRACT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILTER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=4, number=26,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=167,
  serialized_end=233,
)


_RELATION = _descriptor.Descriptor(
  name='Relation',
  full_name='qpe.proto.Relation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='qpe.proto.Relation.op', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relations', full_name='qpe.proto.Relation.relations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='qpe.proto.Relation.rows', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='qpe.proto.Relation.width', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='qpe.proto.Relation.result', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RELATION_OPCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=233,
)

_RELATION.fields_by_name['op'].enum_type = _RELATION_OPCODE
_RELATION.fields_by_name['relations'].message_type = _RELATION
_RELATION_OPCODE.containing_type = _RELATION;
DESCRIPTOR.message_types_by_name['Relation'] = _RELATION

class Relation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RELATION

  # @@protoc_insertion_point(class_scope:qpe.proto.Relation)


# @@protoc_insertion_point(module_scope)
